name: Bug Report
description: Report a bug or unexpected behavior
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: input
    id: command
    attributes:
      label: Command
      description: What command were you running?
      placeholder: "asa campaigns list"
    validations:
      required: true

  - type: textarea
    id: output
    attributes:
      label: Output/Error
      description: The output or error message you received.
      render: shell
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: CLI Version
      description: Output of `asa --version`
      placeholder: "search-ads-cli 0.1.0 (search-ads-api 0.1.0)"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "3.13.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem.
